name: goodlinker_chart
description: A Flutter plugin for creating charts with colored mask area and time xAxis on Android and iOS.
version: 0.0.13
homepage: https://github.com/triplehman3563/goodlinker_chart

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
